### ISSUE TITLE
More webpage improvements

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#267]
- [ ] Use jupyterbook-css on the individual TOI pages (fixes #165 )
- [ ] Disable pointless left sidebar scroll (see https://github.com/executablebooks/sphinx-book-theme/issues/732)
- [ ] open-in-colab button (#233 ) 

Some ✨ extra ✨  stuff that would be nice
- [ ] Add utterances on the individual TOI pages (https://sphinx-book-theme.readthedocs.io/en/stable/reference/comments.html#utterances)
