### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by dfm** [dfm/tess-atlas#45]
I'm looking through the notebook and I *love* what you've been doing @avivajpeyi!! I think we're getting really close. Here are my current suggestions for next steps:

- [x] Get rid of the masking step. This will help with #44 and we don't really need to worry about the speed up, I think. Things are still super fast even with all the data!
- [ ] Better prior choices for the priors and initialization of the noise model. I'm planning on working on this a bit today. More soon.
- [x] I think it would be nice to refactor some of the boilerplate (like plotting etc.) out into the `tess_atlas` module. I'd like the model to still be defined in the notebook, but I think that the boilerplate is a bit distracting now, I think. What would you say?
- [x] (optional) Use [jupytext](https://github.com/mwouts/jupytext) instead of a `.ipynb` for the template since that will make diffing easier.
- [x] Save eccentricity samples somewhere.
- [x] Save the notebook and netcdf files in a subdirectory instead of in one flat directory.
- [x] Make a notebook that demonstrates how to use the netcdf files. Is there enough information in them? Do we also want to pickle the model?
- [x] In the subdirectory it would be nice to save some illustrative static figures too.
- [x] Requirements are out of date (`isochrones` is no longer needed). Let's audit that.
- [x] Fix eccentricity (ref #46 )
- [ ] Single Transit Systems (ref #29 )

**Comment by avivajpeyi** [comment]
@dfm do you have any suggestions for the `better choices for priors`?
